# Generated by Django 3.1.3 on 2020-12-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
